import ExcelJS from 'exceljs';
import { type Profile, type RentLedger, type Expense } from '@/types';
import { type ScheduleHPProperty, getAYLabel } from './itrExport';

/**
 * REHWAS EXCEL GENERATOR
 * 
 * WHAT IT DOES: Generates a multi-sheet Excel workbook formatted for 
 * Indian Income Tax (ITR) filing.
 * 
 * ANALOGY: Like a CA's final binder — Sheet 1 is the summary for the tax form, 
 * Sheet 2 & 3 are the evidence (ledger and receipts) in case of an audit.
 */

// Define extended types for display in Excel
interface RentLedgerExcel extends RentLedger {
  room_title?: string;
  tenant_name?: string;
}

interface ExpenseExcel extends Expense {
  room_title?: string;
}

export async function generateITRExcel(
  landlord: Profile,
  fy: string,
  properties: ScheduleHPProperty[],
  allLedgerEntries: RentLedgerExcel[],
  allExpenses: ExpenseExcel[]
): Promise<Blob> {

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'REHWAS';
  workbook.created = new Date();
  
  // ─── SHEET 1: Schedule HP Summary ───────────────────────────
  const sheet1 = workbook.addWorksheet('Schedule HP Summary');
  
  // Title row
  sheet1.mergeCells('A1:G1');
  sheet1.getCell('A1').value = `REHWAS — Income from House Property`;
  sheet1.getCell('A1').font = { bold: true, size: 14, color: { argb: 'FF10B981' } };
  sheet1.getCell('A1').alignment = { horizontal: 'center' };
  
  sheet1.mergeCells('A2:G2');
  sheet1.getCell('A2').value = `For Assessment Year ${getAYLabel(fy)} | FY ${fy} | For CA Use`;
  sheet1.getCell('A2').font = { italic: true, size: 11 };
  sheet1.getCell('A2').alignment = { horizontal: 'center' };
  
  sheet1.mergeCells('A3:G3');
  sheet1.getCell('A3').value = `Landlord: ${landlord.full_name}`;
  sheet1.getCell('A3').alignment = { horizontal: 'center' };
  
  sheet1.addRow([]); // Spacer
  
  // Header row
  const headerRow = sheet1.addRow([
    'Property / Room',
    'Annual Rent Received (₹)',
    'Municipal Tax Paid (₹)',
    'Net Annual Value (₹)',
    'Std Deduction 30% (₹)',
    'Interest on Loan (₹)',
    'Income from HP (₹)'
  ]);
  headerRow.font = { bold: true };
  headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1FAE5' } };
  
  // Data rows
  let totalIncome = 0;
  for (const prop of properties) {
    const row = sheet1.addRow([
      `${prop.propertyAddress}\n(Tenant: ${prop.tenantName})`,
      prop.annualRentReceived,
      prop.municipalTaxPaid,
      prop.netAnnualValue,
      prop.standardDeduction,
      prop.interestOnLoan,
      prop.incomeFromHP
    ]);
    row.height = 30; // Extra height for the multi-line cell
    row.getCell(1).alignment = { wrapText: true, vertical: 'middle' };
    totalIncome += prop.incomeFromHP;
  }
  
  // Total row
  const totalRow = sheet1.addRow([
    'TOTAL INCOME FROM HOUSE PROPERTY',
    '', '', '', '', '',
    totalIncome
  ]);
  totalRow.font = { bold: true };
  totalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E293B' } };
  totalRow.getCell(7).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  totalRow.getCell(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  
  sheet1.addRow([]);
  sheet1.addRow(['Note: Standard deduction of 30% applied per Section 24(a) of Income Tax Act.']);
  sheet1.addRow(['Note: Verify all figures with your Chartered Accountant before filing ITR.']);
  sheet1.addRow([`Generated by REHWAS on ${new Date().toLocaleDateString('en-IN')}`]);
  
  // Column widths
  sheet1.getColumn(1).width = 35;
  for (let i = 2; i <= 7; i++) {
    sheet1.getColumn(i).width = 22;
  }
  
  // ─── SHEET 2: Monthly Rent Ledger ────────────────────────────
  const sheet2 = workbook.addWorksheet('Monthly Rent Ledger');
  const ledgerHeader = sheet2.addRow(['Month', 'Property', 'Tenant', 'Rent Due (₹)', 'Received (₹)', 'Status', 'Late Fee (₹)']);
  ledgerHeader.font = { bold: true };
  ledgerHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };

  for (const entry of allLedgerEntries) {
    sheet2.addRow([
      entry.month,
      entry.room_title || 'Room',
      entry.tenant_name || 'Tenant',
      entry.amount,
      entry.status === 'paid' ? entry.amount : 0,
      entry.status.toUpperCase(),
      entry.late_fee_applied || 0
    ]);
  }
  sheet2.columns.forEach(col => col.width = 18);
  sheet2.getColumn(2).width = 25;
  sheet2.getColumn(3).width = 25;
  
  // ─── SHEET 3: Expenses Register ──────────────────────────────
  const sheet3 = workbook.addWorksheet('Expenses Register');
  const expenseHeader = sheet3.addRow(['Date', 'Property', 'Category', 'Description', 'Amount (₹)']);
  expenseHeader.font = { bold: true };
  expenseHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF2F2' } };

  for (const expense of allExpenses) {
    sheet3.addRow([
      new Date(expense.expense_date).toLocaleDateString('en-IN'),
      expense.room_title || 'All Properties',
      expense.category.toUpperCase(),
      expense.description || '',
      expense.amount
    ]);
  }
  sheet3.columns.forEach(col => col.width = 18);
  sheet3.getColumn(4).width = 40;
  
  const buffer = await workbook.xlsx.writeBuffer();
  return new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
}
